baseURL = "https://kjperez.com"
googleAnalytics = "UA-175033523-1"
languageCode = "en-us"
title = "Kevin Perez"
theme = "noteworthy"
paginate = 5
summaryLength = 10

[params]
    dateform      = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"

    disableReadOtherPosts = false
    showReadMore = true
    enableSharingButtons = true

    description = "This is a place where I try to make sense of this whole growing up thing."
    keywords = "homepage, portfolio, blog"
    images = [""]

    defaultTheme = "light"

    # Icons
    email = "mailto:hello@kjperez.com"
    linkedin = "https://www.linkedin.com/in/kevin-perez-712b39139/"
    soundcloud = "https://soundcloud.com/kjp62/sets/lunch-break/s-V6S8pRXqqWl"

    # Colors for favicons
    [params.favicon.color]
        mask = "#252627"
        msapplication = "#252627"
        theme = "#252627"

    [params.logo]
        logoText = "Kevin Perez"
        logoHomeLink = "/"
        logoCursorColor = "#446e91"

[author]
    name = "Kevin Perez"

[languages]
  [languages.en]
    title = "Kevin Perez"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Kevin Perez"
      logoHomeLink = "/"

    # There is an About page I have and could use, but it's been deleted.
    # [[menu.main]]
    #    identifier = "about"
    #    name       = "About"
    #    url        = "/about"

    [[menu.main]]
        identifier = "blog"
        name       = "Blog"
        url        = "/posts"


[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

